# Generated by Django 4.2.13 on 2024-05-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review_delete_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pelmeni',
            new_name='Thing',
        ),
    ]
